# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hcb < Formula
  desc "Read-only CLI and MCP server for the HCB v4 API"
  homepage "https://github.com/hackclub/hcb-cli-and-mcp"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hackclub/hcb-cli-and-mcp/releases/download/v0.1.9/hcb_0.1.9_darwin_amd64.tar.gz"
      sha256 "8bca02c08a2417f42b0e1291f817a309abe972c64f659e8cda3a2f9df074509d"

      define_method(:install) do
        bin.install "hcb"
        bin.install "hcb-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hackclub/hcb-cli-and-mcp/releases/download/v0.1.9/hcb_0.1.9_darwin_arm64.tar.gz"
      sha256 "da4ab048aa989f098ade9a1d51a927a862b68208d4c32dca591d06d1626e3e31"

      define_method(:install) do
        bin.install "hcb"
        bin.install "hcb-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hackclub/hcb-cli-and-mcp/releases/download/v0.1.9/hcb_0.1.9_linux_amd64.tar.gz"
      sha256 "2c04fad02b08bd2b13d19ffe0da0180a4e0e21f06345fe4116d3041adae6b0a0"
      define_method(:install) do
        bin.install "hcb"
        bin.install "hcb-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hackclub/hcb-cli-and-mcp/releases/download/v0.1.9/hcb_0.1.9_linux_arm64.tar.gz"
      sha256 "36bb3423bc8baee751f4439746ea53849c43b0406a56bbb0cb657d4b625cd1c5"
      define_method(:install) do
        bin.install "hcb"
        bin.install "hcb-mcp"
      end
    end
  end

  test do
    system "#{bin}/hcb", "version"
  end
end
