# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hcb < Formula
  desc "Read-only CLI and MCP server for the HCB v4 API"
  homepage "https://github.com/hackclub/hcb-cli-and-mcp"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hackclub/hcb-cli-and-mcp/releases/download/v0.1.12/hcb_0.1.12_darwin_amd64.tar.gz"
      sha256 "bed72dbd478e48691838ec959d0deb3f25630985f506c0b3c6946ea39bb38c25"

      define_method(:install) do
        bin.install "hcb"
        bin.install "hcb-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hackclub/hcb-cli-and-mcp/releases/download/v0.1.12/hcb_0.1.12_darwin_arm64.tar.gz"
      sha256 "7ef6c1ed5cf0eefe74d48849dc1e40f86ff9ba7871ed77b13f9bc805fe905258"

      define_method(:install) do
        bin.install "hcb"
        bin.install "hcb-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hackclub/hcb-cli-and-mcp/releases/download/v0.1.12/hcb_0.1.12_linux_amd64.tar.gz"
      sha256 "f69f51b3d30d6ac8da539734a11b5c24d346728b1c0093ef4b0d43104cf00fec"
      define_method(:install) do
        bin.install "hcb"
        bin.install "hcb-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hackclub/hcb-cli-and-mcp/releases/download/v0.1.12/hcb_0.1.12_linux_arm64.tar.gz"
      sha256 "ec9b6ad70a2e6f6a648d4e32dec8da0a766fe4812da9fb58829b90af655b33d0"
      define_method(:install) do
        bin.install "hcb"
        bin.install "hcb-mcp"
      end
    end
  end

  test do
    system "#{bin}/hcb", "version"
  end
end
